### ISSUE TITLE
fn-bvbd-forecast -> fn-bvbd

### ISSUE THREAD

**Issue by ric70x7** [disarm-platform/fn-bvbd-forecast#1]
@HughSt, since we decided not to make forecasts in this application, I think it is better just to name the function as fn-bvbd

**Comment by HughSt** [comment]
I think this has been done?

**Comment by onlyjsmith** [comment]
We don't have a `fn-bvbd-forecast` repo, when you try to access it redirects to `fn-bvbd`, so think it's done.
