### ISSUE TITLE
missing data file

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-bvbd-forecast#2]
The current master branch fails with a 404 printed to the logs. Not sure what file it's trying to retrieve, but it's failing.

We should be returning a better response to the user if the function can't find a file it needs.

The same error appears on the `use-template` branch

**Comment by onlyjsmith** [comment]
Confirm this happens on `master` and `use-template`. @HughSt can you take a look, it's probably a missing data file we're trying to download.

**Comment by HughSt** [comment]
This was an experimental function so I think icebox for the mo

**Comment by onlyjsmith** [comment]
Dropbox file for `tha` covariates is missing.
